name: CI

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

      - name: Git Checkout
        id: git_checkout
        uses: actions/checkout@v2

      - name: Setup Python
        id: setup_python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Setup Test Environment
        id: setup_test_environment
        run: |
          python -m pip install pipenv
          pipenv install --dev

      - name: Test WDL
        id: test_wdl
        shell: bash {0}
        run: |
          # Run tests
          pipenv run python -m pytest

          # This logic accomodates code 5, which is
          # returned by pytest when no tests are run.
          # Feel free to remove it after the first test is added.
          exit $(( $? == 5 ? 0 : $? ))

  tag:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest
    needs: test
    steps:

      - name: Git Checkout
        id: git_checkout
        uses: actions/checkout@v2

      - name: Tag
        id: tag
        uses: mathieudutour/github-tag-action@v4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          release_branches: master

      - name: Zip Sub-workfows
        id: zip_subworkflows
        run: zip -j -r ${{ github.workspace }}/subworkflows.zip ${{ github.workspace }}/subworkflows/*

      - name: Upload Artifacts
        id: upload_artifacts
        uses: actions/upload-artifact@v2
        with:
          name: subworkflows.zip
          path: ${{ github.workspace }}/subworkflows.zip
